# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd0b1666b2882d89ced3c66834e358139865adeb39f14528cf8de1bbb040ffbea89db97faf30c9f2b445b8ef935e239e439d09ff2bf739161bf9e52bffae6eb3

test:
  secret_key_base: 5edccb8c81691694c0b6180808055a444984a004dd8dcc6a36230d1294123bbdec23fe1c01b316fdfe6519b1e8de5b9dfbf4859c39e5edcabcafad09e6549802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
